version: '3'

services:
  open-webui:
    image: sakenism/custom_open-webui
    container_name: open-webui
    env_file:
      - .env
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - custom_network

  pipelines:
    image: sakenism/custom_pipelines
    container_name: pipelines
    ports:
      - "9099:9099"
    volumes:
      - pipelines:/app/pipelines
      - open-webui:/app/backend/data  # This gives pipelines access to open-webui's data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  open-webui:
  pipelines: